---
title: "Test Report"
author: "Matt Bixley"
date: "July 3, 2015"
output: 
  word_document:
    reference_docx: resources/markdown_styles.docx
subtitle: "test setup for Markdown"
abstract: "This document provides an introduction to R Markdown and looks at the use of templates within as MSWord environment"
---
```{r setup, include = F}
knitr::opts_chunk$set(
  echo = TRUE, warning = FALSE, message = FALSE
  )
library(knitr)
library(palmerpenguins)
library(tidyverse)

```


My report starts here.

# Header 1
write a paragraph here

## Header 2
write something else

\pagebreak
### Header 3 - Table  


```{r table, echo = F}
penguins %>% 
  group_by(species) %>% 
  select(contains(c("length", "depth", "mass"))) %>% 
  summarize_all(., mean, na.rm = TRUE) %>%
  kable(caption = "Summarized Data", digits = 2)
```

\pagebreak
#### Header 4 - Plot

```{r plot, echo = T}
penguins %>% 
  ggplot(aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point(aes(colour = species, shape = species), size = 3)
```

