---
title: "Intro to Markdown"
author: "Matt Bixley"
date: "27 August, 2020"
output:
  html_document:
    code_folding: show
    df_print: kable
    highlight: espresso
    number_sections: yes
    theme: readable
    toc: yes
    toc_float: yes
bibliography: resources/markdown.bib
csl: resources/new-zealand-veterinary-journal.csl
subtitle: _writing repoducible reports_
always_allow_html: yes
params:
  island: biscoe
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
#knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
library(palmerpenguins)
library(knitr)
library(janitor)
```

# Objectives

- parameters
- report template
- output

# Data

Read in our paramterized data

```{r data}
penguins <- data <- read_csv(here::here('data', glue::glue(params$island, '.csv'))) %>% 
  clean_names()
```

# Tables  

```{r kableextra}
penguins %>% 
  group_by(species) %>% 
  select(contains(c("length", "depth", "mass"))) %>% 
  summarize_all(., mean, na.rm = TRUE) %>%
  kable(caption = "Summarized Data", format = "html") %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = F, position = "left")
```


## Plots

You can also embed plots, for example:

```{r histogram, fig.cap = "Caption for the plot created", fig.align = "center", warning = FALSE}
flipper_hist <- ggplot(data = penguins, aes(x = flipper_length_mm)) +
  geom_histogram(aes(fill = species), 
                 alpha = 0.5, 
                 position = "identity") +
  scale_fill_manual(values = c("darkorange","purple","cyan4")) +
  theme_minimal() +
  labs(x = "Flipper length (mm)",
       y = "Frequency",
       title = paste0("Flipper lengths on ", unique(penguins$island),  " island"))
flipper_hist
```


